version: '3.8'

services:
  kairos-web:
    image: ghcr.io/kairos-enterprises-nz/kairos-website:${IMAGE_TAG:-main-latest}
    ports:
      - "80"
    networks:
      - edge_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kairos.rule=Host(`kairos.yourdomain.com`)"
      - "traefik.http.routers.kairos.tls=true"
      - "traefik.http.services.kairos.loadbalancer.server.port=80"

networks:
  edge_net:
    external: true