version: '3.8'

services:
  kairos_web:
    image: ghcr.io/kairos-enterprises-nz/kairos-website:${IMAGE_TAG:-main-latest}
    ports:
      - "80"
    networks:
      - edge_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  edge_net:
    external: true