name: Deploy Kairos Website

on:
  push:
    branches: [main]
    paths: 
      - 'src/**'
      - 'public/**'
      - 'Dockerfile'
      - 'package*.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate image tag
        id: tag
        run: |
          echo "image_tag=main-${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "short_sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/kairos-website:${{ steps.tag.outputs.image_tag }}
            ghcr.io/${{ github.repository_owner }}/kairos-website:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Update deployment file
        run: |
          sed -i "s|\${IMAGE_TAG:-latest}|${{ steps.tag.outputs.image_tag }}|" deploy/production.yml
          
      - name: Commit deployment update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add deploy/production.yml
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Deploy Kairos website ${{ steps.tag.outputs.short_sha }}"
            git push
          fi
