name: Deploy Kairos Website

on:
  push:
    branches: [main]
    paths: 
      - 'src/**'
      - 'public/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'package*.json'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate image tag
        id: tag
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "image_tag=main-${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/kairos-website:${{ steps.tag.outputs.image_tag }}
            ghcr.io/${{ github.repository_owner }}/kairos-website:main-latest
            ghcr.io/${{ github.repository_owner }}/kairos-website:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
